import { useState } from "react";
import { useAuth } from "../context/AuthContext";
import { useToast } from "../context/ToastContext";
import api from "../api/axios";

export default function AIRecommendation() {
  const { user } = useAuth();
  const { toast } = useToast();
  const [form, setForm] = useState({
    age: user?.age || "",
    fitnessGoal: user?.fitnessGoal || "Weight Loss",
    experienceLevel: user?.experienceLevel || "Beginner"
  });
  const [recommendation, setRecommendation] = useState(null);
  const [loading, setLoading] = useState(false);

  const GOALS = ["Weight Loss", "Muscle Gain", "Endurance", "Flexibility", "Overall Fitness"];
  const LEVELS = ["Beginner", "Intermediate", "Advanced"];

  const handleSubmit = async (e) => {
    e.preventDefault();
    setLoading(true);
    setRecommendation(null);
    try {
      const res = await api.post("/ai/recommendation", {
        age: Number(form.age),
        fitnessGoal: form.fitnessGoal,
        experienceLevel: form.experienceLevel,
      });
      setRecommendation(res.data.data);
      toast("AI workout plan generated! 🎉", "success");
    } catch (err) {
      toast(err.response?.data?.message || "Failed to generate plan. Check GEMINI_API_KEY.", "error");
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="page-container">
      <div className="page-header">
        <div>
          <h1>🤖 AI <span className="gradient-text">Workout Plan</span></h1>
          <p style={{ color: "var(--text-secondary)", marginTop: "4px", fontSize: "14px" }}>
            Personalized fitness routines generated by Google Gemini AI.
            {user?.age && <span style={{ color: "var(--accent-teal)", marginLeft: "8px" }}>✓ Pre-filled from your profile</span>}
          </p>
        </div>
      </div>

      <div style={{ display: "grid", gridTemplateColumns: "minmax(240px, 1fr) 2fr", gap: "24px", alignItems: "flex-start" }}>
        {/* Form */}
        <div className="glass-card" style={{ padding: "28px" }}>
          <h3 style={{ marginBottom: "6px", fontWeight: 700 }}>Your Fitness Profile</h3>
          {user?.age && <p style={{ fontSize: "12px", color: "var(--accent-teal)", marginBottom: "16px" }}>📌 Auto-filled from your profile</p>}

          <form onSubmit={handleSubmit} style={{ display: "flex", flexDirection: "column", gap: "16px" }}>
            <div className="input-group">
              <label>Age</label>
              <input className="input-field" type="number" min="10" max="100" placeholder="e.g. 25"
                value={form.age} onChange={(e) => setForm({ ...form, age: e.target.value })} required />
            </div>
            <div className="input-group">
              <label>Fitness Goal</label>
              <select className="input-field" value={form.fitnessGoal} onChange={(e) => setForm({ ...form, fitnessGoal: e.target.value })}>
                {GOALS.map(g => <option key={g} value={g}>{g}</option>)}
              </select>
            </div>
            <div className="input-group">
              <label>Experience Level</label>
              <select className="input-field" value={form.experienceLevel} onChange={(e) => setForm({ ...form, experienceLevel: e.target.value })}>
                {LEVELS.map(l => <option key={l} value={l}>{l}</option>)}
              </select>
            </div>
            <button type="submit" className="btn btn-teal" style={{ width: "100%", justifyContent: "center", marginTop: "8px" }} disabled={loading}>
              {loading ? "✨ Generating..." : "✨ Generate AI Routine"}
            </button>
          </form>
        </div>

        {/* Results */}
        <div>
          {loading && (
            <div className="glass-card spinner-wrap" style={{ minHeight: "300px", flexDirection: "column", gap: "16px" }}>
              <div className="spinner" />
              <p style={{ color: "var(--text-secondary)", fontSize: "14px" }}>Consulting Gemini AI coach...</p>
            </div>
          )}

          {!loading && !recommendation && (
            <div className="glass-card empty-state" style={{ minHeight: "300px", display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center" }}>
              <div className="icon">⚡</div>
              <h3>Ready to transform your routine?</h3>
              <p style={{ maxWidth: "340px", fontSize: "14px", marginTop: "6px" }}>Click Generate to receive your custom AI weekly plan.</p>
            </div>
          )}

          {recommendation && (
            <div style={{ display: "flex", flexDirection: "column", gap: "20px" }}>
              {recommendation.motivationalNote && (
                <div className="glass-card" style={{ padding: "20px", borderLeft: "4px solid var(--accent-teal)" }}>
                  <div style={{ fontWeight: 600, color: "var(--accent-teal)", marginBottom: "4px" }}>🧠 Coach's Note</div>
                  <p style={{ fontStyle: "italic" }}>"{recommendation.motivationalNote}"</p>
                </div>
              )}

              {recommendation.weeklyPlan && (
                <div className="glass-card" style={{ padding: "24px" }}>
                  <h3 style={{ marginBottom: "16px", fontWeight: 700 }}>📅 Weekly Schedule</h3>
                  <div style={{ display: "flex", flexDirection: "column", gap: "10px" }}>
                    {recommendation.weeklyPlan.map((dayPlan, i) => (
                      <div key={i} style={{ padding: "14px 16px", borderRadius: "10px", background: "rgba(255,255,255,0.03)", border: "1px solid var(--border)" }}>
                        <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: "6px" }}>
                          <span style={{ fontWeight: 700, color: "var(--accent-teal)" }}>{dayPlan.day}</span>
                          <span className="badge badge-default">{dayPlan.focus}</span>
                        </div>
                        {dayPlan.exercises && <div style={{ fontSize: "13px", color: "var(--text-secondary)" }}>{dayPlan.exercises.join(" • ")}</div>}
                      </div>
                    ))}
                  </div>
                </div>
              )}

              <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "16px" }}>
                {recommendation.suggestedExercises && (
                  <div className="glass-card" style={{ padding: "20px" }}>
                    <h4 style={{ color: "var(--accent-blue)", marginBottom: "12px" }}>🎯 Suggested Exercises</h4>
                    <ul style={{ paddingLeft: "18px", color: "var(--text-secondary)", fontSize: "13px", display: "flex", flexDirection: "column", gap: "6px" }}>
                      {recommendation.suggestedExercises.map((ex, i) => <li key={i}>{ex}</li>)}
                    </ul>
                  </div>
                )}
                {recommendation.safetyTips && (
                  <div className="glass-card" style={{ padding: "20px" }}>
                    <h4 style={{ color: "var(--accent-red)", marginBottom: "12px" }}>🛡️ Safety & Form Tips</h4>
                    <ul style={{ paddingLeft: "18px", color: "var(--text-secondary)", fontSize: "13px", display: "flex", flexDirection: "column", gap: "6px" }}>
                      {recommendation.safetyTips.map((tip, i) => <li key={i}>{tip}</li>)}
                    </ul>
                  </div>
                )}
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
